### PR TITLE
fix: handle internal server error on client

### LINKED ISSUE #13: Deal with rendering issues
_From @satazor on February 19, 2017 12:40_

At the moment, if `render` or similar functions throw an error the following happens:

- On the server-side, the `internal-error` is rendered, which is ok!
- On the client-side, all falls apart with a blank page.

See: https://github.com/facebook/react/issues/2461

_Copied from original issue: moxystudio/react-with-moxy#20_

### PR DESCRIPTION
**Pull request by andregoncalvesdev**
Closes #13

### CODE REVIEW

File: src/entry-server.js [hunk 1]
```diff
@@ -72,6 +72,7 @@ export async function renderError({ err, req, res, buildManifest }) {
         helmet: Helmet.renderStatic(),
         rootHtml,
         buildManifest,
+        isomorphicState: { internalServerError: true },
```
Comment (satazor) [inline src/entry-server.js:75]: Instead of `internalServerError` what if we call it `renderedError: true` or perhaps just `error` and use https://github.com/sindresorhus/serialize-error?

File: src/entry-client.js [hunk 2]
```diff
@@ -15,6 +17,13 @@ history.listen((location) => {
     }
 });
 
+const { internalServerError } = window.__ISOMORPHIC_STATE__ || {};
```
Comment (satazor) [inline src/entry-client.js]: Could we move this to the first declarations? near the `isDev`?

File: src/entry-client.js [hunk 3]
```diff
@@ -15,6 +17,13 @@ history.listen((location) => {
...
+// Set location to /internal-error if we had an internal server error
+const location = internalServerError ? '/internal-error' : undefined;
+
+// Allow the isomorphic state to be garbage-collected on non-dev environments
+!isDev && delete window.__ISOMORPHIC_STATE__;
```
Comment (satazor) [inline src/entry-client.js]: Same as above.

**Review by satazor — CHANGES_REQUESTED** [review]

File: src/entry-server.js (hunk 1 above)
Comment (satazor) [reply src/entry-server.js:75]: Nvm, leave it like this!

File: src/entry-client.js (hunk 3 above)
Comment (andregoncalvesdev) [reply src/entry-client.js]: both updated.

**Review by satazor — APPROVED** [review]
